[package]
name = "infra-ccu-info"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
prometheus = "0.13.4"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
structopt = "0.3.26"
tokio = { version = "1.39.2", features = ["full"] }
