contexts:
  default:
    brokers:
    tls:
      enabled: true
      insecure: false
    sasl:
      enabled: true
      username: <sasl_username>
      password: <sasl_password>
      # optional configure sasl mechanism as plaintext, scram-sha256, scram-sha512, oauth (defaults to plaintext)
      mechanism: scram-sha512