apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: jumpbox
    component: justice
    stage: dev
    tier: tools
  name: jumpbox-postgresql-migration
  namespace: tools
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: jumpbox
      component: justice
      stage: dev
      tier: tools
  template:
    metadata:
      labels:
        app: jumpbox
        component: justice
        stage: dev
        tier: tools
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "karpenter.sh/capacity-type"
                  operator: "In"
                  values: ['on-demand']
                - key: "kubernetes.io/arch"
                  operator: "In"
                  values: ['amd64']
      tolerations:
        - key: CriticalWorkloadsOnly 
          operator: Exists 
      nodeSelector:
        accelbyte.io/workload: CriticalWorkloads
      securityContext:
        runAsUser: 0
      containers:
      - image: 144436415367.dkr.ecr.us-west-2.amazonaws.com/jumpbox-image:ubuntu-20.04-1
        imagePullPolicy: IfNotPresent
        workingDir: /migration
        name: jumpbox
        resources:
          limits:
            memory: "512Mi"
          requests:
            cpu: "300m"
            memory: "512Mi"
        securityContext:
          allowPrivilegeEscalation: true # prevent sudo, etc.
          privileged: true    
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /migration
          name: jumpbox-postgresql-migration
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 0
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: jumpbox-postgresql-migration
    spec:
      storageClassName: gp3-encrypted
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
