apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-ingress-postgresql-policy
  namespace: postgresql
spec:
  podSelector:
    matchLabels:
      app: postgresql
      release: postgresql12
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tools
    - podSelector:
        matchLabels:
          app: jumpbox
          tier: tools
    ports:
    - protocol: TCP
      port: 5432