apiVersion: v1
kind: Service
metadata:
  name: infra-ccu-info
  namespace: justice
  annotations:
    prometheus.io/scrape: "true"      
    prometheus.io/path: /metrics
    prometheus.io/scheme: http
spec:
  selector:
    app: infra-ccu-info
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
